### ISSUE TITLE
There are some bugs in your code

### ISSUE THREAD

**Issue by FlyingRoastDuck** [akibcmi/SAMS#1]
Hi, you have done great work on CWS. However, there are some typos in your code. e.g., https://github.com/akibcmi/SAMS/blob/b17378bb08d445f540ac0cb5680023c2fb710a58/train/prf1.py#L34.
Could you please check your code and fix these typos? Thanks.

**Comment by akibcmi** [comment]
Thank you for your help. 
We have fixed it.

**Comment by akibcmi** [comment]
> Hi, you have done great work on CWS. However, there are some typos in your code. e.g.,
> 
> https://github.com/akibcmi/SAMS/blob/b17378bb08d445f540ac0cb5680023c2fb710a58/train/prf1.py#L34
> 
> .
> Could you please check your code and fix these typos? Thanks.

Thank you very much for your help. We will check our code and fix typos.

**Comment by FlyingRoastDuck** [comment]
By the way, I want to ask a question about the pre-processing of data.  In https://github.com/akibcmi/SAMS/blob/555a3f82d19b2daa4d4ed3fc24abc0264b3c295a/data/data.py#L159. The labels are all set to 1, but why?

**Comment by akibcmi** [comment]
> By the way, I want to ask a question about the pre-processing of data. In
> 
> https://github.com/akibcmi/SAMS/blob/555a3f82d19b2daa4d4ed3fc24abc0264b3c295a/data/data.py#L159
> 
> . The labels are all set to 1, but why?

All gaps between characters in one word are not word boundary. As a result, all these labels are set to 1.

**Comment by FlyingRoastDuck** [comment]
But in your paper, you declare that ”1“ indicates word boundary...
 In your reply, you mean that ”1“ is not word boundary in your code? Thanks.
